const CREATOR_KEY='c3_creator_manager_data',CONTENT_KEY='c3_site_content',PANEL_KEY='c3_shared_panels',MACRO_KEY='c3_activity_macrocategories';
const form=document.querySelector('#creator-form'),listRoot=document.querySelector('#creator-list'),statusRoot=document.querySelector('#status'),activityEditor=document.querySelector('#activity-editor');
const fields=Object.fromEntries(['original-slug','name','slug','category','meta','description','image','territories'].map(id=>[id,document.getElementById(id)]));
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const defaultTerritories=slug=>Object.entries(window.C3_DEFAULT_GEO).flatMap(([area,group])=>group.creators.filter(item=>item[0]===slug).map(item=>({area,region:item[1]})));
const genericDescription=(title,name)=>`${name} propone “${title}” in un formato costruito sulla durata, sul pubblico e sugli obiettivi della manifestazione. Contenuti, scaletta, necessità tecniche e momenti di coinvolgimento vengono concordati prima dell’evento.`;
let creators=Object.values(window.C3_CREATORS).map(item=>({...item,territories:item.territories||defaultTerritories(item.slug)}));
let selectedSlug=creators[0]?.slug||'',siteContent={...window.C3_SITE_CONTENT},panels=JSON.parse(JSON.stringify(window.C3_PANELS||[])),selectedPanelSlug=window.C3_PANELS?.[0]?.slug||'';
let macrocategories=JSON.parse(localStorage.getItem(MACRO_KEY)||'null')||['Host','Cosplay','Panel & talk','Workshop','Performance','Gaming & GdR','Community & contenuti','Attività in fiera'];
const filterInputs=[...document.querySelectorAll('#creator-filters input')];
const inferredFilters=creator=>{if(Array.isArray(creator.filters)&&creator.filters.length)return creator.filters;const value=`${creator.category} ${(creator.activities||[]).map(item=>typeof item==='string'?item:item.title).join(' ')}`.toLowerCase();return [/(fantasy|tolkien|harry potter|mitologia|folklore)/.test(value)&&'fantasy',/(gaming|videogioco|videogame|esport)/.test(value)&&'gaming',/(gdr|gdt|gioco di ruolo|giochi di ruolo|gioco da tavolo|giochi da tavolo|boardgame)/.test(value)&&'gdr-gdt',/(cosplay|prop)/.test(value)&&'cosplay',/(music|musica|concerto|canto|performance|j-pop|k-pop|rock)/.test(value)&&'musica',/(panel|talk|hosting|moderazione|pop culture|cinema|serie)/.test(value)&&'pop',/(divulgazione|storia|arte|tech|psicologia|soccorso|lezione|educazione)/.test(value)&&'divulgazione'].filter(Boolean)};
const slugify=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const parseTerritories=value=>value.split(',').map(v=>v.trim()).filter(Boolean).map(v=>{const [area,...region]=v.split(':');return{area:area.trim().toLowerCase(),region:region.join(':').trim()}}).filter(v=>['nord','centro','sud'].includes(v.area)&&v.region);
const setStatus=(root,message)=>{root.textContent=message;clearTimeout(root.timer);root.timer=setTimeout(()=>root.textContent='',4000)};
const saveCreators=()=>{try{localStorage.setItem(CREATOR_KEY,JSON.stringify(creators));return true}catch{setStatus(statusRoot,'Impossibile salvare: lo spazio per le immagini è pieno. Esporta un backup e usa fotografie più leggere.');return false}};
const macroSelectOptions=selected=>`<option value="">Scegli macroarea</option>${macrocategories.map(item=>`<option value="${escapeHtml(item)}" ${item===selected?'selected':''}>${escapeHtml(item)}</option>`).join('')}`;
function activityRow(activity={title:'',description:'',group:''}){const value=typeof activity==='string'?{title:activity,description:genericDescription(activity,fields.name.value||'Il creator'),group:''}:activity;const group=value.group||'';if(group&&!macrocategories.some(item=>item.toLocaleLowerCase('it')===group.toLocaleLowerCase('it')))macrocategories.push(group);const row=document.createElement('div');row.className='activity-row';row.innerHTML=`<select class="activity-group" aria-label="Macroarea attività">${macroSelectOptions(group)}</select><input class="activity-title" value="${escapeHtml(value.title)}" placeholder="Titolo attività" aria-label="Titolo attività"><textarea class="activity-description" placeholder="Spiegazione dell’attività" aria-label="Descrizione attività">${escapeHtml(value.description)}</textarea><button class="remove-activity" type="button" aria-label="Elimina attività">×</button>`;row.querySelector('.remove-activity').addEventListener('click',()=>row.remove());activityEditor.append(row)}
function readActivities(){return [...activityEditor.querySelectorAll('.activity-row')].map(row=>({group:row.querySelector('.activity-group').value.trim(),title:row.querySelector('.activity-title').value.trim(),description:row.querySelector('.activity-description').value.trim()})).filter(item=>item.title)}
function renderActivities(items=[]){activityEditor.innerHTML='';items.forEach(activityRow);if(!items.length)activityRow()}
const macroList=document.querySelector('#macrocategory-list'),macroOptions=document.querySelector('#macrocategory-options');
function refreshActivityGroupOptions(){activityEditor.querySelectorAll('.activity-group').forEach(select=>{const current=select.value;select.innerHTML=macroSelectOptions(current);select.value=current})}
function saveMacrocategories(){macrocategories=macrocategories.map(item=>item.trim()).filter((item,index,list)=>item&&list.findIndex(other=>other.toLocaleLowerCase('it')===item.toLocaleLowerCase('it'))===index);try{localStorage.setItem(MACRO_KEY,JSON.stringify(macrocategories));renderMacrocategories();refreshActivityGroupOptions();return true}catch{setStatus(statusRoot,'Impossibile salvare le macroaree nel browser.');return false}}
function renderMacrocategories(){macroOptions.innerHTML=macrocategories.map(item=>`<option value="${escapeHtml(item)}"></option>`).join('');macroList.innerHTML=macrocategories.map((item,index)=>`<span class="macrocategory-item"><input value="${escapeHtml(item)}" data-macro-index="${index}" aria-label="Modifica ${escapeHtml(item)}"><button type="button" data-remove-macro="${index}" aria-label="Elimina ${escapeHtml(item)}">×</button></span>`).join('')}
function addMacrocategory(rawValue,{notify=true}={}){const value=rawValue.trim();if(!value)return false;const existing=macrocategories.find(item=>item.toLocaleLowerCase('it')===value.toLocaleLowerCase('it'));if(existing){if(notify)setStatus(statusRoot,`La macroarea “${existing}” esiste già.`);return false}macrocategories.push(value);saveMacrocategories();if(notify)setStatus(statusRoot,`Macroarea “${value}” aggiunta.`);return true}
const newMacroInput=document.querySelector('#new-macrocategory');
document.querySelector('#add-macrocategory').addEventListener('click',()=>{if(addMacrocategory(newMacroInput.value))newMacroInput.value=''});
newMacroInput.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();if(addMacrocategory(newMacroInput.value))newMacroInput.value=''});
macroList.addEventListener('change',event=>{const input=event.target.closest('[data-macro-index]');if(!input)return;const draftActivities=readActivities(),index=Number(input.dataset.macroIndex),old=macrocategories[index],next=input.value.trim();if(!next){renderMacrocategories();return}const duplicate=macrocategories.find((item,itemIndex)=>itemIndex!==index&&item.toLocaleLowerCase('it')===next.toLocaleLowerCase('it'));if(duplicate){setStatus(statusRoot,`La macroarea “${duplicate}” esiste già.`);renderMacrocategories();return}macrocategories[index]=next;draftActivities.forEach(activity=>{if(activity.group===old)activity.group=next});creators.forEach(creator=>(creator.activities||[]).forEach(activity=>{if(activity&&typeof activity==='object'&&activity.group===old)activity.group=next}));saveCreators();saveMacrocategories();renderActivities(draftActivities);setStatus(statusRoot,`Macroarea rinominata in “${next}”.`)});
macroList.addEventListener('click',event=>{const button=event.target.closest('[data-remove-macro]');if(!button)return;const draftActivities=readActivities(),index=Number(button.dataset.removeMacro),removed=macrocategories[index],isUsed=creators.some(creator=>(creator.activities||[]).some(activity=>activity&&typeof activity==='object'&&activity.group===removed))||draftActivities.some(activity=>activity.group===removed);if(isUsed&&!confirm(`La categoria “${removed}” è già utilizzata. Eliminarla e lasciare senza macroarea le attività collegate?`))return;draftActivities.forEach(activity=>{if(activity.group===removed)activity.group=''});creators.forEach(creator=>(creator.activities||[]).forEach(activity=>{if(activity&&typeof activity==='object'&&activity.group===removed)activity.group=''}));macrocategories.splice(index,1);saveCreators();saveMacrocategories();renderActivities(draftActivities);setStatus(statusRoot,`Macroarea “${removed}” eliminata.`)});
renderMacrocategories();
function renderList(filter=''){const query=filter.toLowerCase();listRoot.innerHTML=creators.filter(item=>`${item.name} ${item.category}`.toLowerCase().includes(query)).map(item=>`<button type="button" class="creator-row ${item.slug===selectedSlug?'active':''}" data-slug="${escapeHtml(item.slug)}">${item.image?`<img src="${escapeHtml(item.image)}" alt="">`:`<span class="mini">${escapeHtml(item.name.slice(0,2).toUpperCase())}</span>`}<span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.category)}</small></span></button>`).join('');listRoot.querySelectorAll('.creator-row').forEach(button=>button.addEventListener('click',()=>selectCreator(button.dataset.slug)))}
function selectCreator(slug){const creator=creators.find(item=>item.slug===slug);if(!creator)return;selectedSlug=slug;fields['original-slug'].value=creator.slug;fields.name.value=creator.name;fields.slug.value=creator.slug;fields.category.value=creator.category;fields.meta.value=creator.meta||'';fields.description.value=creator.description;fields.image.value=creator.image||'';fields.territories.value=(creator.territories||[]).map(item=>`${item.area}:${item.region}`).join(', ');const activeFilters=inferredFilters(creator);filterInputs.forEach(input=>input.checked=activeFilters.includes(input.value));renderActivities(creator.activities||[]);document.querySelector('#photo-preview').src=creator.image||'assets/c3-agency-logo.png?v=3';renderList(document.querySelector('#search').value)}
function newCreator(){selectedSlug='';HTMLFormElement.prototype.reset.call(form);fields['original-slug'].value='';fields.image.value='';renderActivities();document.querySelector('#photo-preview').src='assets/c3-agency-logo.png?v=3';renderList(document.querySelector('#search').value);fields.name.focus();setStatus(statusRoot,'Nuova scheda pronta: compila i campi e premi Salva modifiche.')}
function optimizeImage(file,callback){const image=new Image();image.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);callback(canvas.toDataURL('image/jpeg',.8));URL.revokeObjectURL(image.src)};image.src=URL.createObjectURL(file)}
fields.name.addEventListener('input',()=>{if(!fields['original-slug'].value)fields.slug.value=slugify(fields.name.value)});
document.querySelector('#photo').addEventListener('change',event=>{const file=event.target.files[0];if(file)optimizeImage(file,data=>{fields.image.value=data;document.querySelector('#photo-preview').src=data})});
document.querySelector('#add-activity').addEventListener('click',()=>activityRow());
form.addEventListener('submit',event=>{event.preventDefault();const slug=slugify(fields.slug.value||fields.name.value);if(!slug)return;if(creators.some(item=>item.slug===slug&&item.slug!==fields['original-slug'].value)){setStatus(statusRoot,'Questo indirizzo è già utilizzato da un altro creator.');return}const activities=readActivities();activities.forEach(activity=>{if(activity.group)addMacrocategory(activity.group,{notify:false})});const record={slug,name:fields.name.value.trim(),category:fields.category.value.trim(),description:fields.description.value.trim(),meta:fields.meta.value.trim(),image:fields.image.value,activities,territories:parseTerritories(fields.territories.value),filters:filterInputs.filter(input=>input.checked).map(input=>input.value)};const index=creators.findIndex(item=>item.slug===fields['original-slug'].value),previous=index>=0?creators[index]:null;if(index>=0)creators[index]=record;else creators.push(record);if(!saveCreators()){if(index>=0)creators[index]=previous;else creators.pop();return}selectedSlug=slug;selectCreator(slug);setStatus(statusRoot,'Creator, attività, macroaree e filtri salvati.')});
document.querySelector('#new-creator').addEventListener('click',newCreator);document.querySelector('#search').addEventListener('input',e=>renderList(e.target.value));
document.querySelector('#duplicate').addEventListener('click',()=>{const current=creators.find(item=>item.slug===selectedSlug);if(!current)return;fields['original-slug'].value='';fields.name.value=`${current.name} copia`;fields.slug.value=`${current.slug}-copia`;selectedSlug='';renderList();setStatus(statusRoot,'Copia pronta: modifica i dati e premi Salva.')});
document.querySelector('#delete').addEventListener('click',()=>{const index=creators.findIndex(item=>item.slug===selectedSlug);if(index<0||!confirm(`Eliminare ${creators[index].name}?`))return;creators.splice(index,1);saveCreators();selectedSlug=creators[0]?.slug||'';selectedSlug?selectCreator(selectedSlug):newCreator();setStatus(statusRoot,'Creator eliminato.')});
const orderList=document.querySelector('#order-list'),orderStatus=document.querySelector('#order-status');
function renderOrder(){orderList.innerHTML=creators.map((creator,index)=>`<div class="order-row" data-slug="${escapeHtml(creator.slug)}"><span>${String(index+1).padStart(2,'0')}</span><div class="order-person">${creator.image?`<img src="${escapeHtml(creator.image)}" alt="">`:''}<div><b>${escapeHtml(creator.name)}</b><small>${escapeHtml(creator.category)}</small></div></div><div class="order-actions"><button type="button" data-move="top" aria-label="Porta ${escapeHtml(creator.name)} in cima" ${index===0?'disabled':''}>⇈</button><button type="button" data-move="up" aria-label="Sposta ${escapeHtml(creator.name)} su" ${index===0?'disabled':''}>↑</button><button type="button" data-move="down" aria-label="Sposta ${escapeHtml(creator.name)} giù" ${index===creators.length-1?'disabled':''}>↓</button><button type="button" data-move="bottom" aria-label="Porta ${escapeHtml(creator.name)} in fondo" ${index===creators.length-1?'disabled':''}>⇊</button></div></div>`).join('')}
orderList.addEventListener('click',event=>{const button=event.target.closest('button[data-move]');if(!button)return;const row=button.closest('.order-row'),index=creators.findIndex(item=>item.slug===row.dataset.slug);if(index<0)return;const oldOrder=[...creators],target=button.dataset.move==='top'?0:button.dataset.move==='bottom'?creators.length-1:button.dataset.move==='up'?index-1:index+1;const [creator]=creators.splice(index,1);creators.splice(target,0,creator);if(!saveCreators()){creators=oldOrder;return}renderOrder();setStatus(orderStatus,`${creator.name} spostato in posizione ${target+1}.`)});
const panelForm=document.querySelector('#panel-form'),panelList=document.querySelector('#panel-admin-list'),panelStatus=document.querySelector('#panel-status');
const panelFields=Object.fromEntries(['original-slug','title','slug','eyebrow','description','duration','target','ideal','image'].map(key=>[key,document.querySelector(`#panel-${key}`)]));
const participantPicker=document.querySelector('#panel-participant-picker');
participantPicker.innerHTML=creators.map(creator=>`<label class="participant-option"><input type="checkbox" value="${escapeHtml(creator.slug)}"><span>${creator.image?`<img src="${escapeHtml(creator.image)}" alt="">`:''}${escapeHtml(creator.name)}</span></label>`).join('');
const savePanels=()=>{try{localStorage.setItem(PANEL_KEY,JSON.stringify(panels));return true}catch{setStatus(panelStatus,'Impossibile salvare: riduci il peso dell’immagine.');return false}};
function renderPanelList(){panelList.innerHTML=panels.map((panel,index)=>`<div class="panel-admin-row ${panel.slug===selectedPanelSlug?'active':''}" data-panel-slug="${escapeHtml(panel.slug)}"><button type="button" data-select-panel>${escapeHtml(panel.title)}</button><div class="panel-order-buttons"><button type="button" data-panel-move="up" ${index===0?'disabled':''} aria-label="Sposta su">↑</button><button type="button" data-panel-move="down" ${index===panels.length-1?'disabled':''} aria-label="Sposta giù">↓</button></div></div>`).join('')}
function selectPanel(slug){const panel=panels.find(item=>item.slug===slug);if(!panel)return;selectedPanelSlug=slug;Object.entries(panelFields).forEach(([key,input])=>input.value=key==='original-slug'?panel.slug:panel[key]||'');participantPicker.querySelectorAll('input').forEach(input=>input.checked=(panel.participants||[]).includes(input.value));document.querySelector('#panel-photo-preview').src=panel.image||((panel.participants||[]).map(id=>creators.find(item=>item.slug===id)?.image).find(Boolean)||'assets/c3-agency-logo.png?v=3');renderPanelList()}
function newPanel(){selectedPanelSlug='';HTMLFormElement.prototype.reset.call(panelForm);panelFields['original-slug'].value='';panelFields.image.value='';participantPicker.querySelectorAll('input').forEach(input=>input.checked=false);document.querySelector('#panel-photo-preview').src='assets/c3-agency-logo.png?v=3';renderPanelList();panelFields.title.focus()}
panelFields.title.addEventListener('input',()=>{if(!panelFields['original-slug'].value)panelFields.slug.value=slugify(panelFields.title.value)});
document.querySelector('#panel-photo').addEventListener('change',event=>{const file=event.target.files[0];if(file)optimizeImage(file,data=>{panelFields.image.value=data;document.querySelector('#panel-photo-preview').src=data})});
panelForm.addEventListener('submit',event=>{event.preventDefault();const slug=slugify(panelFields.slug.value||panelFields.title.value);if(!slug)return;if(panels.some(item=>item.slug===slug&&item.slug!==panelFields['original-slug'].value)){setStatus(panelStatus,'Questo indirizzo è già usato da un altro panel.');return}const participants=[...participantPicker.querySelectorAll('input:checked')].map(input=>input.value);if(participants.length<2){setStatus(panelStatus,'Seleziona almeno due creator per un panel condiviso.');return}const record={slug,title:panelFields.title.value.trim(),eyebrow:panelFields.eyebrow.value.trim(),description:panelFields.description.value.trim(),participants,duration:panelFields.duration.value.trim(),target:panelFields.target.value.trim(),ideal:panelFields.ideal.value.trim(),image:panelFields.image.value};const index=panels.findIndex(item=>item.slug===panelFields['original-slug'].value);if(index>=0)panels[index]=record;else panels.push(record);if(!savePanels())return;selectedPanelSlug=slug;selectPanel(slug);setStatus(panelStatus,'Panel condiviso salvato.')});
document.querySelector('#new-panel').addEventListener('click',newPanel);
document.querySelector('#delete-panel').addEventListener('click',()=>{const index=panels.findIndex(item=>item.slug===selectedPanelSlug);if(index<0||!confirm(`Eliminare ${panels[index].title}?`))return;panels.splice(index,1);savePanels();selectedPanelSlug=panels[0]?.slug||'';selectedPanelSlug?selectPanel(selectedPanelSlug):newPanel();setStatus(panelStatus,'Panel eliminato.')});
panelList.addEventListener('click',event=>{const row=event.target.closest('.panel-admin-row');if(!row)return;if(event.target.closest('[data-select-panel]')){selectPanel(row.dataset.panelSlug);return}const move=event.target.closest('[data-panel-move]');if(!move)return;const index=panels.findIndex(item=>item.slug===row.dataset.panelSlug),target=index+(move.dataset.panelMove==='up'?-1:1);if(target<0||target>=panels.length)return;[panels[index],panels[target]]=[panels[target],panels[index]];savePanels();renderPanelList();setStatus(panelStatus,'Ordine dei panel aggiornato.')});
const contentSections=[
 ['Header',[['navFormat','Voce Format'],['navCreator','Voce Creator'],['navTerritory','Voce Territorio'],['navMethod','Voce Come funziona'],['navLogistics','Voce Logistica'],['headerCta','Pulsante contatti']]],
 ['Copertina',[['heroEyebrow','Occhiello'],['heroTitle','Titolo'],['heroLead','Testo introduttivo'],['heroPrimary','Pulsante principale'],['heroSecondary','Pulsante secondario'],['heroLabel','Etichetta fotografie']]],
 ['Format',[['formatEyebrow','Occhiello'],['formatTitle','Titolo'],['formatText','Introduzione'],['format1Title','Card 1 · titolo'],['format1Text','Card 1 · testo'],['format1Tag','Card 1 · etichetta'],['format2Title','Card 2 · titolo'],['format2Text','Card 2 · testo'],['format2Tag','Card 2 · etichetta'],['format3Title','Card 3 · titolo'],['format3Text','Card 3 · testo'],['format3Tag','Card 3 · etichetta'],['format4Title','Card 4 · titolo'],['format4Text','Card 4 · testo'],['format4Tag','Card 4 · etichetta']]],
 ['Creator',[['rosterEyebrow','Occhiello'],['rosterTitle','Titolo'],['rosterText','Introduzione'],['filterAll','Filtro Tutti'],['filterFantasy','Filtro Fantasy'],['filterGaming','Filtro Gaming'],['filterRoleplay','Filtro GDR/GDT'],['filterCosplay','Filtro Cosplay'],['filterMusic','Filtro Musica'],['filterPop','Filtro Pop culture'],['filterEducation','Filtro Divulgazione']]],
 ['Panel condivisi',[['sharedPanelEyebrow','Occhiello'],['sharedPanelTitle','Titolo'],['sharedPanelText','Introduzione']]],
 ['Territorio',[['territoryEyebrow','Occhiello'],['territoryTitle','Titolo'],['territoryText','Introduzione']]],
 ['Come funziona',[['methodEyebrow','Occhiello'],['methodTitle','Titolo'],['method1Title','Passaggio 1 · titolo'],['method1Text','Passaggio 1 · testo'],['method2Title','Passaggio 2 · titolo'],['method2Text','Passaggio 2 · testo'],['method3Title','Passaggio 3 · titolo'],['method3Text','Passaggio 3 · testo'],['method4Title','Passaggio 4 · titolo'],['method4Text','Passaggio 4 · testo']]],
 ['Logistica',[['logisticsEyebrow','Occhiello'],['logisticsTitle','Titolo'],['logisticsText','Introduzione'],['logistics1Title','Card 1 · titolo'],['logistics1Text','Card 1 · testo'],['logistics2Title','Card 2 · titolo'],['logistics2Text','Card 2 · testo'],['logistics3Title','Card 3 · titolo'],['logistics3Text','Card 3 · testo'],['logistics4Title','Card 4 · titolo'],['logistics4Text','Card 4 · testo']]],
 ['Contatti',[['contactEmailTarget','Email destinataria'],['contactWhatsappTarget','Numero WhatsApp destinatario'],['contactEyebrow','Occhiello'],['contactTitle','Titolo'],['contactText','Introduzione'],['contactFormTitle','Titolo modulo'],['contactName','Campo nome'],['contactEmail','Campo email'],['contactEvent','Campo evento'],['contactCity','Campo città'],['contactDates','Campo date'],['contactAudience','Campo affluenza'],['contactAreas','Campo aree'],['contactBudget','Campo budget'],['contactInterest','Campo interesse'],['contactPhone','Campo telefono'],['contactEmailButton','Pulsante email'],['contactWhatsappButton','Pulsante WhatsApp'],['contactPrivacy','Nota privacy']]],
 ['Footer',[['footerCompany','Ragione sociale'],['footerAddress','Indirizzo'],['footerTax','Partita IVA e PEC'],['footerReserved','Collegamento area riservata'],['footerTop','Collegamento torna su']]]
];
const contentFields=contentSections.flatMap(section=>section[1]);
const siteFields=document.querySelector('#site-fields'),coverGrid=document.querySelector('#cover-grid');
siteFields.innerHTML=contentSections.map(([section,items],index)=>`<details class="content-section" ${index===0?'open':''}><summary><strong>${section}</strong><span>${items.length} testi</span></summary><div class="site-grid">${items.map(([key,label])=>`<div class="field ${key.endsWith('Text')||key==='heroLead'?'full':''}"><label for="content-${key}">${label}</label><textarea id="content-${key}" data-content-key="${key}"></textarea></div>`).join('')}</div></details>`).join('');
coverGrid.innerHTML=[1,2,3].map(number=>`<div class="cover-card"><img id="cover-preview-${number}" alt="Anteprima copertina ${number}"><label class="button ghost file-button">Cambia foto ${number}<input type="file" accept="image/*" data-cover="heroImage${number}"></label></div>`).join('');
function renderSiteForm(){contentFields.forEach(([key])=>document.querySelector(`[data-content-key="${key}"]`).value=siteContent[key]||'');[1,2,3].forEach(number=>document.querySelector(`#cover-preview-${number}`).src=siteContent[`heroImage${number}`])}
coverGrid.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',event=>{const file=event.target.files[0];if(file)optimizeImage(file,data=>{siteContent[input.dataset.cover]=data;renderSiteForm()})}));
document.querySelector('#site-form').addEventListener('submit',event=>{event.preventDefault();contentFields.forEach(([key])=>siteContent[key]=document.querySelector(`[data-content-key="${key}"]`).value.trim());localStorage.setItem(CONTENT_KEY,JSON.stringify(siteContent));setStatus(document.querySelector('#site-status'),'Pagina iniziale aggiornata.')});
document.querySelector('#reset-site').addEventListener('click',()=>{if(!confirm('Ripristinare testi e copertine iniziali?'))return;siteContent={...window.C3_SITE_CONTENT_DEFAULTS};localStorage.removeItem(CONTENT_KEY);renderSiteForm();setStatus(document.querySelector('#site-status'),'Contenuti iniziali ripristinati.')});
document.querySelector('#password-form').addEventListener('submit',async event=>{event.preventDefault();const current=document.querySelector('#current-password').value,next=document.querySelector('#new-password').value,confirmation=document.querySelector('#confirm-password').value,root=document.querySelector('#password-status');if(next!==confirmation){setStatus(root,'Le nuove password non coincidono.');return}const {data:{user}}=await C3_SUPABASE.auth.getUser();const {error:checkError}=await C3_SUPABASE.auth.signInWithPassword({email:user.email,password:current});if(checkError){setStatus(root,'La password attuale non è corretta.');return}const {error:updateError}=await C3_SUPABASE.auth.updateUser({password:next});if(updateError){setStatus(root,updateError.message);return}event.target.reset();setStatus(root,'Password Supabase aggiornata.')});
document.querySelector('#logout').addEventListener('click',async()=>{await C3_SUPABASE.auth.signOut();location.replace('login.html')});
document.querySelectorAll('.admin-nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.admin-nav button').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.admin-panel').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.panelContent!==button.dataset.panel));if(button.dataset.panel==='order')renderOrder()}));
document.querySelector('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({creators,siteContent,panels,macrocategories},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`c3-sito-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();setTimeout(()=>{URL.revokeObjectURL(link.href);link.remove()},1000);setStatus(statusRoot,'Backup completo esportato.')});
document.querySelector('#import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());creators=Array.isArray(data)?data:data.creators;if(!Array.isArray(creators))throw new Error();siteContent=data.siteContent||siteContent;panels=Array.isArray(data.panels)?data.panels:panels;macrocategories=Array.isArray(data.macrocategories)&&data.macrocategories.length?data.macrocategories:macrocategories;saveCreators();savePanels();saveMacrocategories();localStorage.setItem(CONTENT_KEY,JSON.stringify(siteContent));selectedSlug=creators[0]?.slug||'';selectedPanelSlug=panels[0]?.slug||'';renderList();renderPanelList();renderSiteForm();selectedSlug&&selectCreator(selectedSlug);selectedPanelSlug&&selectPanel(selectedPanelSlug);setStatus(statusRoot,'Backup completo importato.')}catch{setStatus(statusRoot,'Il file selezionato non è un backup valido.')}event.target.value=''});
document.querySelector('#reset').addEventListener('click',()=>{if(!confirm('Ripristinare tutti i creator iniziali?'))return;localStorage.removeItem(CREATOR_KEY);location.reload()});
renderList();renderOrder();renderPanelList();renderSiteForm();selectedSlug?selectCreator(selectedSlug):newCreator();selectedPanelSlug&&selectPanel(selectedPanelSlug);
