(()=>{
  const KEY='c3_cookie_preferences_v1';
  const config=window.C3_ANALYTICS_CONFIG||{};
  window.dataLayer=window.dataLayer||[];
  window.gtag=window.gtag||function(){dataLayer.push(arguments)};
  gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
  const loadAnalytics=()=>{if(!/^G-[A-Z0-9]+$/i.test(config.measurementId||'')||document.querySelector('script[data-c3-ga4]'))return;const script=document.createElement('script');script.async=true;script.dataset.c3Ga4='true';script.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(config.measurementId)}`;document.head.append(script);gtag('js',new Date());gtag('config',config.measurementId,{anonymize_ip:true})};
  const apply=choice=>{const granted=choice?.analytics===true;gtag('consent','update',{analytics_storage:granted?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});if(granted)loadAnalytics()};
  const style=document.createElement('style');style.textContent=`.cookie-panel{position:fixed;inset:auto 18px 18px;z-index:9999;width:min(620px,calc(100% - 36px));margin:auto;background:#fff;color:#08152f;border:1px solid #d7e0f1;border-radius:22px;padding:24px;box-shadow:0 24px 80px rgba(5,18,45,.3);font-family:Manrope,Arial,sans-serif}.cookie-panel[hidden]{display:none}.cookie-panel h2{font:22px/1.05 'Archivo Black',Manrope;margin:0 0 10px}.cookie-panel p{font-size:13px;line-height:1.55;color:#52617b;margin:0}.cookie-panel a{color:#27539f;font-weight:800}.cookie-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.cookie-actions button{border:1px solid #d7e0f1;border-radius:999px;padding:11px 16px;background:#edf2fb;color:#27539f;font:800 12px Manrope;cursor:pointer}.cookie-actions .accept{background:#f2b408;color:#08152f;border-color:#f2b408}.cookie-preferences{margin-top:16px;padding-top:14px;border-top:1px solid #d7e0f1}.cookie-preferences label{display:flex;align-items:center;gap:10px;font-size:13px;font-weight:800}.cookie-preferences input{width:19px;height:19px;accent-color:#27539f}.cookie-settings-link{border:0;background:none;color:inherit;text-decoration:underline;cursor:pointer;font:inherit;padding:0}@media(max-width:520px){.cookie-panel{inset:auto 10px 10px;width:calc(100% - 20px);padding:20px}.cookie-actions button{flex:1 1 120px}}`;document.head.append(style);
  const panel=document.createElement('aside');panel.className='cookie-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','cookie-title');panel.innerHTML=`<h2 id="cookie-title">Le tue preferenze contano.</h2><p>Usiamo strumenti tecnici necessari al sito. Con il tuo consenso potremo inoltre utilizzare Google Analytics 4 per capire, in forma statistica, come viene visitato il sito. <a href="cookie-policy.html">Leggi la Cookie Policy</a>.</p><div class="cookie-preferences" hidden><label><input id="cookie-analytics" type="checkbox"> Consenti cookie e misurazione statistica</label></div><div class="cookie-actions"><button type="button" data-cookie="reject">Rifiuta</button><button type="button" data-cookie="settings">Preferenze</button><button type="button" class="accept" data-cookie="accept">Accetta</button><button type="button" class="accept" data-cookie="save" hidden>Salva preferenze</button></div>`;document.body.append(panel);
  const preferences=panel.querySelector('.cookie-preferences'),analytics=panel.querySelector('#cookie-analytics'),save=panel.querySelector('[data-cookie="save"]');
  const persist=value=>{localStorage.setItem(KEY,JSON.stringify({...value,updatedAt:new Date().toISOString()}));apply(value);panel.hidden=true};
  panel.addEventListener('click',event=>{const action=event.target.closest('[data-cookie]')?.dataset.cookie;if(action==='accept')persist({necessary:true,analytics:true});if(action==='reject')persist({necessary:true,analytics:false});if(action==='settings'){preferences.hidden=false;save.hidden=false;analytics.checked=read()?.analytics===true}if(action==='save')persist({necessary:true,analytics:analytics.checked})});
  document.addEventListener('click',event=>{if(event.target.closest('[data-open-cookie-settings]')){event.preventDefault();const current=read();analytics.checked=current?.analytics===true;preferences.hidden=false;save.hidden=false;panel.hidden=false}});
  const current=read();if(current){apply(current);panel.hidden=true}else panel.hidden=false;
})();
