window.C3_DEFAULT_PANELS=[
  {slug:'romantasy-fantasy',title:'Romantasy & Fantasy',eyebrow:'Il boom del genere · panel sul fenomeno del Romantasy',description:'Un viaggio nel genere che ha conquistato BookTok e le classifiche mondiali. Esploreremo cosa distingue il Romantasy dal Fantasy tradizionale, scoprendo perché questo fenomeno ci piace tanto.',participants:['beatrice-lorenzi','lo-scribacchino'],duration:'60 minuti + Q&A opzionale',target:'18–50 · lettori Romantasy/Fantasy',ideal:'Slot trend · area cultura pop',image:''},
  {slug:'doppiaggio-sul-web',title:'Doppiaggio sul Web',eyebrow:'Panel a tutto doppiaggio',description:'Un panel interattivo dedicato al mondo del doppiaggio: tecniche, curiosità e il lavoro della voce tra animazione, web e cultura pop. Alcuni volontari del pubblico salgono sul palco e vengono doppiati dal vivo, rendendo l’incontro dinamico e inaspettato.',participants:['inazuma-sensei','ludo-thorn'],duration:'60 minuti + Q&A opzionale',target:'16–40 · doppiaggio, anime e cultura pop',ideal:'Slot trend · area cultura pop',image:''},
  {slug:'armonie-stregate',title:'Armonie Stregate',eyebrow:'Panel narrativo-musicale sulla storia delle streghe',description:'Divulgazione storica e mitologica si intrecciano alla musica dal vivo in un’esperienza immersiva. Da Ecate alla magia, da Medea e Grimilde a Viviana di Avalon, Galadriel e le figure veggenti, con brani come Once Upon a Dream, Road to Camelot e Down the Witches’ Road.',participants:['cristiana-nerdarte','carla-grimaldi'],duration:'60–75 minuti',target:'18–40 · fantasy, mitologia e GDR',ideal:'Main stage pomeridiano · slot di richiamo',image:''},
  {slug:'millennials-fantasy',title:'Millennial’s Fantasy',eyebrow:'Le storie che hanno cambiato le nostre vite',description:'Un panel nostalgico e analitico sulle saghe fantasy e young adult che hanno formato i millennials tra gli anni 2000 e 2010. Dall’eroismo all’identità, analizzeremo i temi ricorrenti, l’impatto culturale e il modo in cui queste storie hanno plasmato il fantasy contemporaneo.',participants:['lo-scribacchino','golgota','cristiana-nerdarte'],duration:'60 minuti + Q&A opzionale',target:'25–50 · millennials e pubblico trasversale',ideal:'Panel premium · fascia pomeridiana-serale',image:''},
  {slug:'cosplay-in-terra-di-mezzo',title:'Cosplay in Terra di Mezzo',eyebrow:'Panel a tema Signore degli Anelli',description:'Un incontro pratico-creativo sulla nascita di un cosplay tolkieniano: personaggio, silhouette, tessuti, accessori, pose e reference emotive. Il racconto si completa con il contesto narrativo e i dettagli che rendono un costume davvero coerente con l’universo di Tolkien.',participants:['faenel','golgota'],duration:'60 minuti + Q&A opzionale',target:'18–50 · lettori fantasy',ideal:'Slot trend · area cultura pop',image:''},
  {slug:'j-k-cartoon',title:'J/K Cartoon',eyebrow:'Concerto J-pop, K-pop e sigle anime',description:'Le opening degli anime più famosi adattate in italiano, le sigle dei cartoni classici e una selezione J-pop e K-pop. Klyo porta voce e performance, mentre i Team Rocker accompagnano dal vivo e accendono il palco con medley tutti da ballare.',participants:['itsklyo','team-rocker'],duration:'60–90 minuti',target:'14–35 · anime, manga e cosplayer',ideal:'Main stage · evento serale o chiusura giornata',image:''}
];
try{
  let saved=JSON.parse(localStorage.getItem('c3_shared_panels')||'null');
  if(Array.isArray(saved)&&!localStorage.getItem('c3_panels_catalogue_fix_v1')){saved=saved.filter(panel=>!['dal-mito-al-multiverso','cosplay-dal-concept-al-palco'].includes(panel.slug));localStorage.setItem('c3_panels_catalogue_fix_v1','1')}
  if(Array.isArray(saved)&&!localStorage.getItem('c3_panels_pdf_catalogue_v2')){const present=new Set(saved.map(panel=>panel.slug));window.C3_DEFAULT_PANELS.forEach(panel=>{if(!present.has(panel.slug))saved.push(JSON.parse(JSON.stringify(panel)))});localStorage.setItem('c3_shared_panels',JSON.stringify(saved));localStorage.setItem('c3_panels_pdf_catalogue_v2','1')}
  window.C3_PANELS=Array.isArray(saved)?saved:JSON.parse(JSON.stringify(window.C3_DEFAULT_PANELS));
}catch{window.C3_PANELS=JSON.parse(JSON.stringify(window.C3_DEFAULT_PANELS))}
