window.C3_SITE_CONTENT_DEFAULTS={
navFormat:'Format',navCreator:'Creator',navTerritory:'Territorio',navMethod:'Come funziona',navLogistics:'Logistica',headerCta:'Parliamo della tua fiera',
heroEyebrow:'Creator package · fiere & festival',heroTitle:'Il palco che la tua community ricorderà.',heroLead:'Creator, artisti e divulgatori già abituati al pubblico dal vivo. Costruiamo un palinsesto su misura tra fantasy, pop culture, musica, gaming e cosplay.',heroPrimary:'Scopri il roster',heroSecondary:'Esplora i format',heroLabel:'Tre linguaggi. Un solo palco.',heroImage1:'assets/beatrice.jpg',heroImage2:'assets/cristiana.jpg',heroImage3:'assets/scribacchino.jpg',
formatEyebrow:'Un palinsesto, molte possibilità',formatTitle:'Format che accendono ogni area.',formatText:'Ogni proposta è acquistabile singolarmente oppure integrata in un pacchetto: più attività, un’unica regia editoriale e logistica.',
format1Title:'Panel & talk',format1Text:'Approfondimenti, interviste e conversazioni guidate da creator autorevoli e coinvolgenti.',format1Tag:'Pop culture · Fantasy · Cinema',format2Title:'Show & concerti',format2Text:'Performance musicali, doppiaggio live e spettacoli pensati per il main stage.',format2Tag:'Anime · K-pop · Rock · Folk',format3Title:'Workshop',format3Text:'Esperienze pratiche su prop-making, cosplay, gaming, content creation e storytelling.',format3Tag:'Learning by doing',format4Title:'Hosting & contest',format4Text:'Presentazione, moderazione, quiz, meet & greet e giurie cosplay con ritmo da palco.',format4Tag:'Pubblico sempre al centro',
rosterEyebrow:'Il roster completo',rosterTitle:'Trova il volto giusto.',rosterText:'Filtra l’intero roster per area. Il cast viene poi definito in base a target, tono, territorio e budget della manifestazione.',filterAll:'Tutti',filterFantasy:'Fantasy',filterGaming:'Gaming',filterRoleplay:'GDR/GDT',filterCosplay:'Cosplay',filterMusic:'Musica',filterPop:'Pop culture',filterEducation:'Divulgazione',
sharedPanelEyebrow:'Più creator, un’unica esperienza',sharedPanelTitle:'Panel condivisi.',sharedPanelText:'Incontri costruiti intorno a prospettive diverse, per trasformare un tema in una conversazione coinvolgente e memorabile.',
territoryEyebrow:'Da nord a sud',territoryTitle:'Creator vicini alla tua fiera.',territoryText:'Consulta il roster per area geografica. I profili con più basi operative compaiono nelle diverse zone in cui sono disponibili.',
methodEyebrow:'Collaborazione semplice',methodTitle:'Una proposta che si adatta alla tua fiera.',method1Title:'Raccontaci l’evento',method1Text:'Pubblico, dimensioni, aree, date e obiettivi.',method2Title:'Componiamo il cast',method2Text:'Selezioniamo creator e format coerenti con il palinsesto.',method3Title:'Ottimizziamo',method3Text:'Più attività con gli stessi volti riducono costi e complessità.',method4Title:'Andiamo in scena',method4Text:'Professionisti già abituati a palco, pubblico e imprevisti del live.',
logisticsEyebrow:'Logistica coordinata',logisticsTitle:'Più attività. Meno complessità.',logisticsText:'Gestiamo la presenza dei creator con un modello semplice e modulare, pensato per alleggerire l’organizzazione della fiera e ottimizzare il budget.',logistics1Title:'Un unico coordinamento',logistics1Text:'Cast, disponibilità e attività vengono costruiti come un unico palinsesto coerente.',logistics2Title:'Viaggio e alloggio',logistics2Text:'La proposta comprende cachet e rimborso delle spese di viaggio e pernottamento.',logistics3Title:'Più format, più valore',logistics3Text:'Dalla seconda attività dello stesso creator applichiamo uno sconto, riducendo costi e passaggi logistici.',logistics4Title:'Presenza continuativa',logistics4Text:'Gli stessi volti possono accompagnare panel, workshop, palco e area community durante l’evento.',
contactEyebrow:'La prossima fiera può partire da qui',contactTitle:'Costruiamo insieme il tuo prossimo sold out.',contactText:'Compila le prime informazioni: al termine puoi inviarle tramite email oppure aprire la richiesta già pronta su WhatsApp.',contactFormTitle:'Raccontaci il tuo evento',contactName:'Nome e ruolo *',contactEmail:'Email *',contactEvent:'Nome dell’evento *',contactCity:'Città e location *',contactDates:'Date previste *',contactAudience:'Affluenza stimata',contactAreas:'Aree tematiche',contactBudget:'Budget indicativo',contactInterest:'Creator o format di interesse',contactPhone:'Numero di cellulare *',contactEmailButton:'Invia via email',contactWhatsappButton:'Invia su WhatsApp',contactPrivacy:'I dati vengono registrati da C3 Agency per rispondere alla tua richiesta e inviati sul canale che scegli.',
contactEmailTarget:'info@c3agency.it',contactWhatsappTarget:'393513448497',footerCompany:'C3 Agency SRL',footerAddress:'Via Roma 30 · 81022 Casagiove (CE)',footerTax:'P. IVA 04959500614 · PEC: C3agency@pec.it',footerReserved:'Area riservata',footerTop:'Torna su ↑'
};
try{window.C3_SITE_CONTENT={...window.C3_SITE_CONTENT_DEFAULTS,...JSON.parse(localStorage.getItem('c3_site_content')||'{}')}}catch{window.C3_SITE_CONTENT={...window.C3_SITE_CONTENT_DEFAULTS}}
